### ISSUE TITLE
Error after updating to V1.0.0

### ISSUE THREAD

**Issue by ddsim27** [nitaybz/homebridge-cool-automation#13]
Socket errors after updating:

[7/8/2023, 10:04:05 AM] [homebridge-cool-automation] Sending Command: ls2
Error: Socket is closed
    at new NodeError (node:internal/errors:400:5)
    at Socket._writeGeneric (node:net:913:8)
    at Socket._write (node:net:935:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at /homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:66:10
    at new Promise (<anonymous>)
    at sendCommand (/homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:35:9)
    at Object.getDevices (/homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:14:11)

**Comment by oogje** [comment]
Likewise:
[7/9/2023, 11:44:04 PM] [CoolAutomation] Sending Command: ls2
[7/9/2023, 11:44:04 PM] Error: Socket is closed
    at new NodeError (node:internal/errors:372:5)
    at Socket._writeGeneric (node:net:807:8)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /usr/local/lib/node_modules/homebridge-cool-automation/coolAutomation/api.js:66:10
    at new Promise (<anonymous>)
    at sendCommand (/usr/local/lib/node_modules/homebridge-cool-automation/coolAutomation/api.js:35:9)
    at Object.getDevices (/usr/local/lib/node_modules/homebridge-cool-automation/coolAutomation/api.js:14:11)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-cool-automation/index.js:103:35)
[7/9/2023, 11:44:04 PM] Got SIGTERM, shutting down Homebridge...

**Comment by gordonxman** [comment]
Similarly:
[7/15/2023, 8:25:24 AM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-cool-automation) is running on port 30373.
Error: Socket is closed
    at new NodeError (node:internal/errors:400:5)
    at Socket._writeGeneric (node:net:913:8)
    at Socket._write (node:net:935:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at /homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:66:10
    at new Promise (<anonymous>)
    at sendCommand (/homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:35:9)
    at Object.getDevices (/homebridge/node_modules/homebridge-cool-automation/coolAutomation/api.js:14:11)
[7/15/2023, 8:25:25 AM] [homebridge-cool-automation] Child bridge process ended
[7/15/2023, 8:25:25 AM] [homebridge-cool-automation] Process Ended. Code: 1, Signal: null

**Comment by kavinb** [comment]
Hi, im also facing a similar issue after updating to 1.0.0. I had to downgrade  to 0.7 again.

**Comment by adrianmihai83** [comment]
same

**Comment by nitaybz** [comment]
please check the latest version

**Comment by pjf60** [comment]
Thanks for the help on this but the latest version still has tthe same error. I founf 0.7 woks for me.

**Comment by nitaybz** [comment]
did you try 1.0.1 ?

**Comment by pjf60** [comment]
I think so but let me have another try.

**Comment by pjf60** [comment]
Yes, just upgraded and all good.
