### ISSUE TITLE
Permission Denied when installing homebridge-cool-automation on Synology NAS Homebridge

### ISSUE THREAD

**Issue by kavinb** [nitaybz/homebridge-cool-automation#6]
I am using your Cool Automation app for home bridge. I first tried installing on my iMac and it worked perfectly. Now trying to replicate the build on my Synology NAS and am facing an issue when installing. Please see the error codes below: 

[7/21/2021, 12:46:22 AM] [Homebridge UI] Starting terminal session
[7/21/2021, 12:46:23 AM] ====================
[7/21/2021, 12:46:23 AM] ERROR LOADING PLUGIN homebridge-cool-automation:
[7/21/2021, 12:46:23 AM] Error: EACCES: permission denied, mkdir 'log'
    at Object.mkdirSync (fs.js:1009:3)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-cool-automation/node_modules/tcp-client/log/index.js:12:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-cool-automation/node_modules/tcp-client/lib/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
[7/21/2021, 12:46:23 AM] ====================
[7/21/2021, 12:46:23 AM] Loaded plugin: homebridge-dummy@0.5.0
[7/21/2021, 12:46:23 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[7/21/2021, 12:46:23 AM] ---
[7/21/2021, 12:46:23 AM] Loaded plugin: homebridge-config-ui-x@4.41.1
[7/21/2021, 12:46:23 AM] Registering platform 'homebridge-config-ui-x.config'
[7/21/2021, 12:46:23 AM] ---
[7/21/2021, 12:46:23 AM] Loading 2 platforms...
[7/21/2021, 12:46:23 AM] [Config] Initializing config platform...
[7/21/2021, 12:46:23 AM] [Config] Running in Service Mode
[7/21/2021, 12:46:23 AM] No plugin was found for the platform "CoolAutomation" in your config.json. Please make sure the corresponding plugin is installed correctly.

Please let me know where I’m going wrong. I tried adding “--unsafe-perm=true --allow-root” at the end of sudo npm install -g homebridge-cool-automation but to no avail. 

Thanks in advanced for building this great plugin and assisting me.

**Comment by nitaybz** [comment]
I think that the issue is coming from the user running homebridge not having permissions to file system

**Comment by nitaybz** [comment]
probably coming from the tcp-client library I was using... I uploaded a new version 1.0.0 using native nodejs library that should not create this issue
